inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

# プロジェクト固有のカスタマイズ
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/seeds.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'db/seeds.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*'
    - 'db/seeds.rb'
